### ISSUE TITLE
Remove Requirement for Tags to Exist in tag-antenna Script

### ISSUE THREAD

**Issue by kbmorris** [francoisverges/semfio-ekahau#3]
Hello, I've worked out a method to eliminate the requirement for tagKeys.json and/or individual tags to exist in the Ekahau Pro file. The method adds the tagKeys structure when tagKeys.json is not found in the Ekahau file; and adds tagKey entries for tags when the tag is not found. Would you accept a pull request for this added functionality?

**Comment by francoisverges** [comment]
I would be interested to know how you are doing it!
